# language: node_js
# node_js:
#   - stable
# install:
#   - npm install
# script:
#   - npm test

  # chrome headless

language: node_js
node_js:
  - 12
services:
  - xvfb
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

script: karma start karma.config.js --single-run